/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.ifpe.hosp3.view;

import java.sql.*;
import com.br.ifpe.hosp3.connection.ConexaoMysql;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Thaysa Gomes
 */
public class TelaFuncionario extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Cria nova tela de Funcionário
     *
     * @throws java.io.IOException
     */
    public TelaFuncionario() throws IOException {
        initComponents();

        connection = ConexaoMysql.getConexaoMySQL();
    }
    
    /**
     * 
     * Método para consulta dados de Funcionário
     */
    private void consultar() {
        String sql = "select * from funcionario where nome=?";

        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, txtNomeFunc.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                txtCpfFunc.setText(rs.getString(3));
                txtEmailFunc.setText(rs.getString(5));
                txtTelFunc.setText(rs.getString(6));
                txtCodFunc.setText(rs.getString(7));
                txtPassFunc.setText(rs.getString(8));
            } else {
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado");
                txtNomeFunc.setText(null);
                txtCpfFunc.setText(null);
                txtEmailFunc.setText(null);
                txtTelFunc.setText(null);
                txtCodFunc.setText(null);
                txtPassFunc.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * 
     * Método para adicionar dados de Funcionário
     */
    private void adicionar() {
        String sql = "insert into funcionario(id, nome, cpf, endereco_id, email, telefone, codigo, palavra_passe) values(?,?,?,?,?,?,?,?)";

        try {
            pst = connection.prepareStatement(sql);
            pst.setString(2, txtNomeFunc.getText());
            pst.setString(3, txtCpfFunc.getText());
            pst.setString(4, txtRuaFunc.getText());
            pst.setString(5, txtEmailFunc.getText());
            pst.setString(6, txtTelFunc.getText());
            pst.setString(7, txtCodFunc.getText());
            pst.setString(8, txtPassFunc.getText());

            if ((txtNomeFunc.getText().isEmpty()) || (txtCpfFunc.getText().isEmpty()) || (txtRuaFunc.getText().isEmpty()) || (txtEmailFunc.getText().isEmpty()) || (txtTelFunc.getText().isEmpty()) || (txtCodFunc.getText().isEmpty()) || (txtPassFunc.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Insira as informações em todos os campos.");
            } else {
                int adicionado = pst.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário não pôde ser cadastrado. Tente novamente.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * 
     * Método para alterar dados de Funcionário
     */
    public void alterar(){
        String sql = "update funcionario set nome=?, cpf=?, endereco_id=?, email=?, telefone=?, codigo=?, palavra_passe=? where id=?";
        
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, txtNomeFunc.getText());
            pst.setString(2, txtCpfFunc.getText());
            pst.setString(3, txtRuaFunc.getText());
            pst.setString(4, txtEmailFunc.getText());
            pst.setString(5, txtTelFunc.getText());
            pst.setString(6, txtCodFunc.getText());
            pst.setString(7, txtPassFunc.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeFunc = new javax.swing.JLabel();
        lblCpfFunc = new javax.swing.JLabel();
        lblEndIdFunc = new javax.swing.JLabel();
        lblEmailFunc = new javax.swing.JLabel();
        lblTelFunc = new javax.swing.JLabel();
        lblCodFunc = new javax.swing.JLabel();
        lblPassFunc = new javax.swing.JLabel();
        txtNomeFunc = new javax.swing.JTextField();
        txtCpfFunc = new javax.swing.JTextField();
        txtRuaFunc = new javax.swing.JTextField();
        txtEmailFunc = new javax.swing.JTextField();
        txtTelFunc = new javax.swing.JTextField();
        txtCodFunc = new javax.swing.JTextField();
        txtPassFunc = new javax.swing.JTextField();
        btnAddFunc = new javax.swing.JButton();
        btnEditFunc = new javax.swing.JButton();
        btnSearchFunc = new javax.swing.JButton();
        btnDelFunc = new javax.swing.JButton();
        txtNumFunc = new javax.swing.JTextField();
        txtCepFunc = new javax.swing.JTextField();
        txtPaisFunc = new javax.swing.JTextField();
        txtBairroFunc = new javax.swing.JTextField();
        txtCidadeFunc = new javax.swing.JTextField();
        txtCompFunc = new javax.swing.JTextField();
        lblNumFunc = new javax.swing.JLabel();
        lblCepFunc = new javax.swing.JLabel();
        lblBairroFunc = new javax.swing.JLabel();
        lblPaisFunc = new javax.swing.JLabel();
        lblCidadeFunc = new javax.swing.JLabel();
        lblCompFunc = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Funcionário");

        lblNomeFunc.setText("Nome");

        lblCpfFunc.setText("CPF");

        lblEndIdFunc.setText("Rua");

        lblEmailFunc.setText("E-mail");

        lblTelFunc.setText("Telefone");

        lblCodFunc.setText("Código");

        lblPassFunc.setText("Palavra passe");

        txtNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFuncActionPerformed(evt);
            }
        });

        txtRuaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaFuncActionPerformed(evt);
            }
        });

        btnAddFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N /*iconfinder*/
        btnAddFunc.setToolTipText("Adicionar");
        btnAddFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddFunc.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAddFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuncActionPerformed(evt);
            }
        });

        btnEditFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N /*iconfinder*/
        btnEditFunc.setToolTipText("Editar");
        btnEditFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditFunc.setPreferredSize(new java.awt.Dimension(80, 80));

        btnSearchFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N /*iconfinder*/
        btnSearchFunc.setToolTipText("Pesquisar");
        btnSearchFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchFunc.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSearchFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFuncActionPerformed(evt);
            }
        });

        btnDelFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N /*iconfinder*/
        btnDelFunc.setToolTipText("Deletar");
        btnDelFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelFunc.setPreferredSize(new java.awt.Dimension(80, 80));

        txtPaisFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisFuncActionPerformed(evt);
            }
        });

        lblNumFunc.setText("Número");

        lblCepFunc.setText("CEP");

        lblBairroFunc.setText("Bairro");

        lblPaisFunc.setText("País");

        lblCidadeFunc.setText("Cidade");

        lblCompFunc.setText("Complemento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeFunc)
                            .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCpfFunc)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodFunc)
                                .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(165, 165, 165)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPassFunc)
                                .addComponent(txtPassFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblEndIdFunc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(btnEditFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btnSearchFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnDelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCepFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(lblCepFunc)
                                .addComponent(lblCompFunc)
                                .addComponent(txtCompFunc)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEmailFunc)
                                            .addComponent(lblPaisFunc, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPaisFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCidadeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmailFunc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(94, 94, 94)
                                            .addComponent(lblCidadeFunc)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblBairroFunc))
                                        .addComponent(txtRuaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelFunc)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNumFunc)
                                        .addGap(46, 46, 46))
                                    .addComponent(txtTelFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpfFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndIdFunc)
                    .addComponent(lblNumFunc)
                    .addComponent(lblCepFunc))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBairroFunc)
                        .addGap(263, 263, 263))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCompFunc)
                                .addComponent(lblPaisFunc, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblCidadeFunc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPaisFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCidadeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCompFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelFunc)
                            .addComponent(lblEmailFunc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodFunc)
                            .addComponent(lblPassFunc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBairroFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncActionPerformed

    private void txtRuaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaFuncActionPerformed

    private void btnSearchFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFuncActionPerformed
        consultar();
    }//GEN-LAST:event_btnSearchFuncActionPerformed

    private void btnAddFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuncActionPerformed
        adicionar();
    }//GEN-LAST:event_btnAddFuncActionPerformed

    private void txtPaisFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisFuncActionPerformed

    private void txtNomeFuncActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFunc;
    private javax.swing.JButton btnDelFunc;
    private javax.swing.JButton btnEditFunc;
    private javax.swing.JButton btnSearchFunc;
    private javax.swing.JLabel lblBairroFunc;
    private javax.swing.JLabel lblCepFunc;
    private javax.swing.JLabel lblCidadeFunc;
    private javax.swing.JLabel lblCodFunc;
    private javax.swing.JLabel lblCompFunc;
    private javax.swing.JLabel lblCpfFunc;
    private javax.swing.JLabel lblEmailFunc;
    private javax.swing.JLabel lblEndIdFunc;
    private javax.swing.JLabel lblNomeFunc;
    private javax.swing.JLabel lblNumFunc;
    private javax.swing.JLabel lblPaisFunc;
    private javax.swing.JLabel lblPassFunc;
    private javax.swing.JLabel lblTelFunc;
    private javax.swing.JTextField txtBairroFunc;
    private javax.swing.JTextField txtCepFunc;
    private javax.swing.JTextField txtCidadeFunc;
    private javax.swing.JTextField txtCodFunc;
    private javax.swing.JTextField txtCompFunc;
    private javax.swing.JTextField txtCpfFunc;
    private javax.swing.JTextField txtEmailFunc;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtNumFunc;
    private javax.swing.JTextField txtPaisFunc;
    private javax.swing.JTextField txtPassFunc;
    private javax.swing.JTextField txtRuaFunc;
    private javax.swing.JTextField txtTelFunc;
    // End of variables declaration//GEN-END:variables
}
