/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.ifpe.hosp3.view;
import java.sql.*;
import com.br.ifpe.hosp3.connection.ConexaoMysql;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Cursor;
/**
 *
 * @author Thaysa Gomes
 */
public class TelaCriarCadastro extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Cria nova tela de Cadastrar para primeiro acesso ao sistema
     *
     * @throws java.io.IOException
     */
    public TelaCriarCadastro() throws IOException {
        initComponents();
        connection = ConexaoMysql.getConexaoMySQL();
    }
    
    private void adicionar() {
        String sql = "insert into funcionario(id, nome, cpf, endereco_id, email, telefone, codigo, palavra_passe) values(?,?,?,?,?,?,?,?)";

        try {
            pst = connection.prepareStatement(sql);
            pst.setString(2, txtNomeCadastro.getText());
            pst.setString(3, txtCpfCadastro.getText());
            pst.setString(4, txtRuaCadastro.getText());
            pst.setString(5, txtEmailCadastro.getText());
            pst.setString(6, txtTelCadastro.getText());
            pst.setString(7, txtCodCadastro.getText());
            pst.setString(8, txtPassCadastro.getText());

            if ((txtNomeCadastro.getText().isEmpty()) || (txtCpfCadastro.getText().isEmpty()) || (txtRuaCadastro.getText().isEmpty()) || (txtEmailCadastro.getText().isEmpty()) || (txtTelCadastro.getText().isEmpty()) || (txtCodCadastro.getText().isEmpty()) || (txtPassCadastro.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Insira as informações em todos os campos.");
            } else {
                int adicionado = pst.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário não pôde ser cadastrado. Tente novamente.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeCadastro = new javax.swing.JLabel();
        txtNomeCadastro = new javax.swing.JTextField();
        lblCpfCadastro = new javax.swing.JLabel();
        txtCpfCadastro = new javax.swing.JTextField();
        lblRuaCadastro = new javax.swing.JLabel();
        txtRuaCadastro = new javax.swing.JTextField();
        lblNumCadastro = new javax.swing.JLabel();
        txtNumCadastro = new javax.swing.JTextField();
        lblCepCadastro = new javax.swing.JLabel();
        txtCepCadastro = new javax.swing.JTextField();
        lblPaisCadastro = new javax.swing.JLabel();
        txtPaisCadastro = new javax.swing.JTextField();
        lblCidadeCadastro = new javax.swing.JLabel();
        txtCidadeCadastro = new javax.swing.JTextField();
        lblBairroCadastro = new javax.swing.JLabel();
        txtBairroCadastro = new javax.swing.JTextField();
        lblCompCadastro = new javax.swing.JLabel();
        txtCompCadastro = new javax.swing.JTextField();
        lblEmailCadastro = new javax.swing.JLabel();
        txtEmailCadastro = new javax.swing.JTextField();
        lblTelCadastro = new javax.swing.JLabel();
        txtTelCadastro = new javax.swing.JTextField();
        lblCodCadastro = new javax.swing.JLabel();
        txtCodCadastro = new javax.swing.JTextField();
        lblPassCadastro = new javax.swing.JLabel();
        txtPassCadastro = new javax.swing.JTextField();
        btnAddCadastro = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnVoltar.setFont(new Font("Tahoma", Font.PLAIN, 12));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Primeiro acesso");

        lblNomeCadastro.setText("Nome");

        txtNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadastroActionPerformed(evt);
            }
        });

        lblCpfCadastro.setText("CPF");

        lblRuaCadastro.setText("Rua");

        txtRuaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaCadastroActionPerformed(evt);
            }
        });

        lblNumCadastro.setText("Número");

        lblCepCadastro.setText("CEP");

        lblPaisCadastro.setText("País");

        txtPaisCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisCadastroActionPerformed(evt);
            }
        });

        lblCidadeCadastro.setText("Cidade");

        lblBairroCadastro.setText("Bairro");

        lblCompCadastro.setText("Complemento");

        lblEmailCadastro.setText("E-mail");

        lblTelCadastro.setText("Telefone");

        lblCodCadastro.setText("Código");

        lblPassCadastro.setText("Palavra passe");

        btnAddCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddCadastro.setText("Adicionar");
        btnAddCadastro.setToolTipText("Adicionar");
        btnAddCadastro.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        btnAddCadastro.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAddCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCadastroActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(45)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(lblNomeCadastro)
        								.addComponent(txtNomeCadastro, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE))
        							.addGap(51)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(txtCpfCadastro, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
        								.addComponent(lblCpfCadastro)))
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        							.addGroup(layout.createSequentialGroup()
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(lblCodCadastro)
        									.addComponent(txtCodCadastro, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE))
        								.addGap(165)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(lblPassCadastro)
        									.addComponent(txtPassCadastro, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)))
        							.addComponent(lblRuaCadastro, Alignment.LEADING)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(txtBairroCadastro, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
        								.addGap(70)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(txtCepCadastro, GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        									.addComponent(lblCepCadastro)
        									.addComponent(lblCompCadastro)
        									.addComponent(txtCompCadastro)))
        							.addGroup(layout.createSequentialGroup()
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addGroup(layout.createSequentialGroup()
        										.addGroup(layout.createParallelGroup(Alignment.LEADING)
        											.addComponent(txtEmailCadastro, Alignment.TRAILING)
        											.addComponent(lblPaisCadastro)
        											.addGroup(layout.createSequentialGroup()
        												.addComponent(txtPaisCadastro, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        												.addGap(18)
        												.addComponent(txtCidadeCadastro, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        											.addComponent(lblEmailCadastro))
        										.addPreferredGap(ComponentPlacement.RELATED))
        									.addGroup(layout.createSequentialGroup()
        										.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        											.addGroup(layout.createSequentialGroup()
        												.addGap(94)
        												.addComponent(lblCidadeCadastro)
        												.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        												.addComponent(lblBairroCadastro))
        											.addComponent(txtRuaCadastro, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE))
        										.addGap(23)))
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(txtNumCadastro, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        									.addComponent(lblTelCadastro)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(lblNumCadastro)
        											.addGap(46))
        										.addComponent(txtTelCadastro, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)))))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(109)
        					.addComponent(btnAddCadastro, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        					.addGap(79)
        					.addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)))
        			.addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(50)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblNomeCadastro)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txtNomeCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblCpfCadastro)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txtCpfCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblRuaCadastro)
        				.addComponent(lblNumCadastro)
        				.addComponent(lblCepCadastro))
        			.addGap(4)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtRuaCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtNumCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtCepCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblBairroCadastro)
        					.addPreferredGap(ComponentPlacement.RELATED, 175, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(lblCompCadastro)
        							.addComponent(lblPaisCadastro, Alignment.TRAILING))
        						.addComponent(lblCidadeCadastro, Alignment.TRAILING))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(txtPaisCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtCidadeCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtBairroCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(txtCompCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblTelCadastro)
        						.addComponent(lblEmailCadastro))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtEmailCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtTelCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblCodCadastro)
        						.addComponent(lblPassCadastro))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtCodCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtPassCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(47)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(btnVoltar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnAddCadastro, GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        			.addGap(55))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadastroActionPerformed

    private void txtRuaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaCadastroActionPerformed

    private void txtPaisCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisCadastroActionPerformed

    private void btnAddCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCadastroActionPerformed
    adicionar();
    }//GEN-LAST:event_btnAddCadastroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    this.dispose();        
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCriarCadastro().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TelaCriarCadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCadastro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblBairroCadastro;
    private javax.swing.JLabel lblCepCadastro;
    private javax.swing.JLabel lblCidadeCadastro;
    private javax.swing.JLabel lblCodCadastro;
    private javax.swing.JLabel lblCompCadastro;
    private javax.swing.JLabel lblCpfCadastro;
    private javax.swing.JLabel lblEmailCadastro;
    private javax.swing.JLabel lblNomeCadastro;
    private javax.swing.JLabel lblNumCadastro;
    private javax.swing.JLabel lblPaisCadastro;
    private javax.swing.JLabel lblPassCadastro;
    private javax.swing.JLabel lblRuaCadastro;
    private javax.swing.JLabel lblTelCadastro;
    private javax.swing.JTextField txtBairroCadastro;
    private javax.swing.JTextField txtCepCadastro;
    private javax.swing.JTextField txtCidadeCadastro;
    private javax.swing.JTextField txtCodCadastro;
    private javax.swing.JTextField txtCompCadastro;
    private javax.swing.JTextField txtCpfCadastro;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JTextField txtNomeCadastro;
    private javax.swing.JTextField txtNumCadastro;
    private javax.swing.JTextField txtPaisCadastro;
    private javax.swing.JTextField txtPassCadastro;
    private javax.swing.JTextField txtRuaCadastro;
    private javax.swing.JTextField txtTelCadastro;
    // End of variables declaration//GEN-END:variables
}