/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.ifpe.hosp3.view;

import java.sql.*;
import com.br.ifpe.hosp3.connection.ConexaoMysql;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Thaysa Gomes
 */
public class TelaFuncionario extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Cria nova tela de Funcionário
     *
     * @throws java.io.IOException
     */
    public TelaFuncionario() throws IOException {
        initComponents();

        connection = ConexaoMysql.getConexaoMySQL();
    }
    
    /**
     * 
     * Método para consulta dados de Funcionário
     */
    private void consultar() {
        String sql = "select * from funcionario where nome=?";

        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, txtNomeFunc.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                txtCpfFunc.setText(rs.getString(3));
                txtEmailFunc.setText(rs.getString(5));
                txtTelFunc.setText(rs.getString(6));
                txtCodFunc.setText(rs.getString(7));
                txtPassFunc.setText(rs.getString(8));
            } else {
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado");
                txtNomeFunc.setText(null);
                txtCpfFunc.setText(null);
                txtEmailFunc.setText(null);
                txtTelFunc.setText(null);
                txtCodFunc.setText(null);
                txtPassFunc.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * 
     * Método para adicionar dados de Funcionário
     */
    private void adicionar() {
        String sql = "insert into funcionario(id, nome, cpf, endereco_id, email, telefone, codigo, palavra_passe) values(?,?,?,?,?,?,?,?)";

        try {
            pst = connection.prepareStatement(sql);
            pst.setString(2, txtNomeFunc.getText());
            pst.setString(3, txtCpfFunc.getText());
            pst.setString(4, txtRuaFunc.getText());
            pst.setString(5, txtEmailFunc.getText());
            pst.setString(6, txtTelFunc.getText());
            pst.setString(7, txtCodFunc.getText());
            pst.setString(8, txtPassFunc.getText());

            if ((txtNomeFunc.getText().isEmpty()) || (txtCpfFunc.getText().isEmpty()) || (txtRuaFunc.getText().isEmpty()) || (txtEmailFunc.getText().isEmpty()) || (txtTelFunc.getText().isEmpty()) || (txtCodFunc.getText().isEmpty()) || (txtPassFunc.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Insira as informações em todos os campos.");
            } else {
                int adicionado = pst.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário não pôde ser cadastrado. Tente novamente.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * 
     * Método para alterar dados de Funcionário
     */
    public void alterar(){
        String sql = "update funcionario set nome=?, cpf=?, endereco_id=?, email=?, telefone=?, codigo=?, palavra_passe=? where id=?";
        
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, txtNomeFunc.getText());
            pst.setString(2, txtCpfFunc.getText());
            pst.setString(3, txtRuaFunc.getText());
            pst.setString(4, txtEmailFunc.getText());
            pst.setString(5, txtTelFunc.getText());
            pst.setString(6, txtCodFunc.getText());
            pst.setString(7, txtPassFunc.getText());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeFunc = new javax.swing.JLabel();
        lblNomeFunc.setBounds(45, 50, 27, 14);
        lblCpfFunc = new javax.swing.JLabel();
        lblCpfFunc.setBounds(316, 50, 19, 14);
        lblEndIdFunc = new javax.swing.JLabel();
        lblEndIdFunc.setBounds(45, 108, 19, 14);
        lblEmailFunc = new javax.swing.JLabel();
        lblEmailFunc.setBounds(45, 280, 28, 14);
        lblTelFunc = new javax.swing.JLabel();
        lblTelFunc.setBounds(288, 280, 42, 14);
        lblCodFunc = new javax.swing.JLabel();
        lblCodFunc.setBounds(45, 331, 33, 14);
        lblPassFunc = new javax.swing.JLabel();
        lblPassFunc.setBounds(288, 331, 67, 14);
        txtNomeFunc = new javax.swing.JTextField();
        txtNomeFunc.setBounds(45, 70, 220, 20);
        txtCpfFunc = new javax.swing.JTextField();
        txtCpfFunc.setBounds(316, 70, 162, 20);
        txtRuaFunc = new javax.swing.JTextField();
        txtRuaFunc.setBounds(45, 126, 220, 20);
        txtEmailFunc = new javax.swing.JTextField();
        txtEmailFunc.setBounds(45, 300, 195, 20);
        txtTelFunc = new javax.swing.JTextField();
        txtTelFunc.setBounds(288, 300, 190, 20);
        txtCodFunc = new javax.swing.JTextField();
        txtCodFunc.setBounds(45, 351, 78, 20);
        txtPassFunc = new javax.swing.JTextField();
        txtPassFunc.setBounds(288, 351, 190, 20);
        btnAddFunc = new javax.swing.JButton();
        btnAddFunc.setBounds(398, 404, 80, 42);
        txtNumFunc = new javax.swing.JTextField();
        txtNumFunc.setBounds(288, 126, 47, 20);
        txtCepFunc = new javax.swing.JTextField();
        txtCepFunc.setBounds(381, 126, 97, 20);
        txtPaisFunc = new javax.swing.JTextField();
        txtPaisFunc.setBounds(177, 181, 76, 20);
        txtBairroFunc = new javax.swing.JTextField();
        txtBairroFunc.setBounds(45, 181, 117, 20);
        txtCidadeFunc = new javax.swing.JTextField();
        txtCidadeFunc.setBounds(263, 181, 100, 20);
        txtCompFunc = new javax.swing.JTextField();
        txtCompFunc.setBounds(45, 249, 195, 20);
        lblNumFunc = new javax.swing.JLabel();
        lblNumFunc.setBounds(288, 108, 37, 14);
        lblCepFunc = new javax.swing.JLabel();
        lblCepFunc.setBounds(381, 108, 19, 14);
        lblBairroFunc = new javax.swing.JLabel();
        lblBairroFunc.setBounds(45, 161, 28, 14);
        lblPaisFunc = new javax.swing.JLabel();
        lblPaisFunc.setBounds(177, 161, 19, 14);
        lblCidadeFunc = new javax.swing.JLabel();
        lblCidadeFunc.setBounds(263, 161, 47, 14);
        lblCompFunc = new javax.swing.JLabel();
        lblCompFunc.setBounds(45, 229, 195, 14);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Funcionário");

        lblNomeFunc.setText("Nome");

        lblCpfFunc.setText("CPF");

        lblEndIdFunc.setText("Rua");

        lblEmailFunc.setText("E-mail");

        lblTelFunc.setText("Telefone");

        lblCodFunc.setText("Código");

        lblPassFunc.setText("Palavra passe");

        txtNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFuncActionPerformed(evt);
            }
        });

        txtRuaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaFuncActionPerformed(evt);
            }
        });

        btnAddFunc.setText("Adicionar");
        btnAddFunc.setToolTipText("Adicionar");
        btnAddFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddFunc.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAddFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuncActionPerformed(evt);
            }
        });

        txtPaisFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisFuncActionPerformed(evt);
            }
        });

        lblNumFunc.setText("Número");

        lblCepFunc.setText("CEP");

        lblBairroFunc.setText("Bairro");

        lblPaisFunc.setText("País");

        lblCidadeFunc.setText("Cidade");

        lblCompFunc.setText("Complemento");
        getContentPane().setLayout(null);
        getContentPane().add(lblNomeFunc);
        getContentPane().add(txtNomeFunc);
        getContentPane().add(txtCpfFunc);
        getContentPane().add(lblCpfFunc);
        getContentPane().add(lblCodFunc);
        getContentPane().add(txtCodFunc);
        getContentPane().add(lblPassFunc);
        getContentPane().add(txtPassFunc);
        getContentPane().add(lblEndIdFunc);
        getContentPane().add(txtBairroFunc);
        getContentPane().add(txtCepFunc);
        getContentPane().add(lblCepFunc);
        getContentPane().add(lblCompFunc);
        getContentPane().add(txtCompFunc);
        getContentPane().add(txtEmailFunc);
        getContentPane().add(lblPaisFunc);
        getContentPane().add(txtPaisFunc);
        getContentPane().add(txtCidadeFunc);
        getContentPane().add(lblEmailFunc);
        getContentPane().add(lblCidadeFunc);
        getContentPane().add(lblBairroFunc);
        getContentPane().add(txtRuaFunc);
        getContentPane().add(txtNumFunc);
        getContentPane().add(lblTelFunc);
        getContentPane().add(lblNumFunc);
        getContentPane().add(txtTelFunc);
        getContentPane().add(btnAddFunc);
        
        lblEstadoFunc = new JLabel("Estado");
        lblEstadoFunc.setBounds(381, 161, 46, 14);
        getContentPane().add(lblEstadoFunc);
        
        txtEstadoFunc = new JTextField();
        txtEstadoFunc.setBounds(381, 181, 97, 20);
        getContentPane().add(txtEstadoFunc);
        txtEstadoFunc.setColumns(10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRuaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaFuncActionPerformed

    private void btnAddFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuncActionPerformed
        adicionar();
    }//GEN-LAST:event_btnAddFuncActionPerformed

    private void txtPaisFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisFuncActionPerformed

    private void txtNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFunc;
    private javax.swing.JLabel lblBairroFunc;
    private javax.swing.JLabel lblCepFunc;
    private javax.swing.JLabel lblCidadeFunc;
    private javax.swing.JLabel lblCodFunc;
    private javax.swing.JLabel lblCompFunc;
    private javax.swing.JLabel lblCpfFunc;
    private javax.swing.JLabel lblEmailFunc;
    private javax.swing.JLabel lblEndIdFunc;
    private javax.swing.JLabel lblNomeFunc;
    private javax.swing.JLabel lblNumFunc;
    private javax.swing.JLabel lblPaisFunc;
    private javax.swing.JLabel lblPassFunc;
    private javax.swing.JLabel lblTelFunc;
    private javax.swing.JTextField txtBairroFunc;
    private javax.swing.JTextField txtCepFunc;
    private javax.swing.JTextField txtCidadeFunc;
    private javax.swing.JTextField txtCodFunc;
    private javax.swing.JTextField txtCompFunc;
    private javax.swing.JTextField txtCpfFunc;
    private javax.swing.JTextField txtEmailFunc;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtNumFunc;
    private javax.swing.JTextField txtPaisFunc;
    private javax.swing.JTextField txtPassFunc;
    private javax.swing.JTextField txtRuaFunc;
    private javax.swing.JTextField txtTelFunc;
    private JLabel lblEstadoFunc;
    private JTextField txtEstadoFunc;
    // End of variables declaration//GEN-END:variables
}
