<<<<<<< HEAD
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.ifpe.hosp3.view;
import java.awt.Color;

import javax.swing.JOptionPane;

import com.br.ifpe.hosp3.controller.HospedeController;
import com.br.ifpe.hosp3.model.Endereco;
import com.br.ifpe.hosp3.model.Hospede;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JInternalFrame;

/**
 *
 * @author Thaysa Gomes
 */
public class TelaCriarHospede extends javax.swing.JInternalFrame {


	/**
	 * Método de ação na interface para criar hospede 
	 * 
	 * @param hospede {@link Hospede}
	 * @param endereco {@link Endereco}
	 * 
	 * @throws Exception
	 **/
	public void criarHospede(Hospede hospede, Endereco endereco) {
		try {
			HospedeController.criarHospede(hospede, endereco);
			JOptionPane.showMessageDialog(null, "Hospede " + hospede.getNome() + "Cadastrado com Sucesso!");
			this.dispose();
		}catch(Exception e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
			this.dispose();
		}
		
	}

    /**
     * Cria nova tela de Hóspede
     */
    public TelaCriarHospede() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	lblBairroHospede = new javax.swing.JLabel();
    	txtBairroHospede = new javax.swing.JTextField();
    	
    	lblCompHospede = new javax.swing.JLabel();
    	txtCompHospede = new javax.swing.JTextField();
    	
    	lblRuaHospede = new javax.swing.JLabel();
    	txtRuaHospede = new javax.swing.JTextField();
    	
    	lblNumHospede = new javax.swing.JLabel();
    	txtNumHospede = new javax.swing.JTextField();
    	

    	lblEstadoHospede = new javax.swing.JLabel();
    	txtEstadoHospede = new javax.swing.JTextField();
    	
    	lblCidadeHospede = new javax.swing.JLabel();
    	txtCidadeHospede = new javax.swing.JTextField();
    	
    	lblPaisHospede = new javax.swing.JLabel();
    	txtPaisHospede = new javax.swing.JTextField();
    	
    	lblCepHospede = new javax.swing.JLabel();
    	txtCepHospede = new javax.swing.JTextField();
        
    	lblBuscaCpfHospede = new javax.swing.JLabel();
    	txtBuscaCpfHospede = new javax.swing.JTextField();
    	
        lblTelHospede = new javax.swing.JLabel();
        txtTelHospede = new javax.swing.JTextField();
        
        lblNomeHospede = new javax.swing.JLabel();
        txtNomeHospede = new javax.swing.JTextField();
        
        lblEmailHospede = new javax.swing.JLabel();
        txtEmailHospede = new javax.swing.JTextField();
        
        lblPassHospede = new javax.swing.JLabel();
        txtPassHospede = new javax.swing.JPasswordField(10);
        
        btnAddHospede = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Hóspede");

        //btnAddHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("./../resources/img/"))); // NOI18N /*iconfinder*/
        btnAddHospede.setText("Adicionar");
        
        Color cor = new Color(46,139, 87);
        btnAddHospede.setBackground(cor);
        btnAddHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddHospede.setPreferredSize(new java.awt.Dimension(80, 50));

       

        lblBuscaCpfHospede.setText("CPF");

        lblRuaHospede.setText("Rua");

        lblNumHospede.setText("Número");

        lblEmailHospede.setText("E-mail");

        lblCepHospede.setText("CEP");

        lblTelHospede.setText("Telefone");

        lblBairroHospede.setText("Bairro");

        lblPaisHospede.setText("País");

        lblPassHospede.setText("Palavra passe");

        lblCidadeHospede.setText("Cidade");

        txtNomeHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeHospedeActionPerformed(evt);
            }
        });

        lblCompHospede.setText("Complemento");

        txtRuaHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaHospedeActionPerformed(evt);
            }
           
        });

        txtPaisHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisHospedeActionPerformed(evt);
            }
        });
        
       //Adicionando evento para botão de salvar ouvir
        btnAddHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnAddHospedeAction(evt);
            }
        });
        
        lblNomeHospede.setText("Nome");
        
        JLabel label = new JLabel();
        label.setText("CPF");
        
        textField = new JTextField();
        
        JButton btnPesquisar = new JButton("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(25)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(txtBuscaCpfHospede, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(btnPesquisar))
        						.addComponent(lblBuscaCpfHospede)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addComponent(lblRuaHospede, Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(txtBairroHospede, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
        									.addGap(70)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        										.addComponent(txtCepHospede)
        										.addComponent(lblCepHospede)
        										.addComponent(lblCompHospede)
        										.addComponent(txtCompHospede, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)))
        								.addGroup(layout.createSequentialGroup()
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(lblPaisHospede)
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(txtPaisHospede, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(txtCidadeHospede, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        										.addGroup(layout.createSequentialGroup()
        											.addGap(94)
        											.addComponent(lblCidadeHospede)))
        									.addGap(91)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(txtNumHospede, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        										.addComponent(lblNumHospede))
        									.addGap(46))
        								.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(lblNomeHospede)
        										.addComponent(txtNomeHospede, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE))
        									.addGap(26)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(label, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
        											.addGap(201))
        										.addComponent(txtRuaHospede, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE))
        									.addGap(18)
        									.addGroup(layout.createSequentialGroup()
        										.addGap(10)
        										.addGroup(layout.createParallelGroup(Alignment.LEADING)
        											.addComponent(txtEmailHospede, Alignment.TRAILING, 198, 198, 198)
        											.addComponent(lblEmailHospede)))))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblBairroHospede)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(lblPassHospede)
        									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(btnAddHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtPassHospede, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)))
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(lblTelHospede)
        									.addComponent(txtTelHospede, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(57)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE))
        				.addGap(564)
        				.addGap(564))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(30)
        			.addComponent(lblBuscaCpfHospede)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtBuscaCpfHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnPesquisar))
        			.addGap(81)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(lblNomeHospede)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(txtNomeHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(lblEmailHospede)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(txtEmailHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addGroup(layout.createSequentialGroup()
        						.addGap(20)
        						.addComponent(txtRuaHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(label)
        						.addGap(26))))
        			.addGap(6)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(19)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(lblRuaHospede)
        								.addComponent(lblNumHospede)
        								.addComponent(lblCepHospede))
        							.addGap(4)
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(txtNumHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtCepHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(lblCompHospede)
        									.addComponent(lblPaisHospede, Alignment.TRAILING))
        								.addComponent(lblCidadeHospede, Alignment.TRAILING))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(txtCompHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED))
        								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        									.addComponent(txtPaisHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        									.addComponent(txtCidadeHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        									.addComponent(txtBairroHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        						.addComponent(lblBairroHospede))
        					.addGap(41)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblTelHospede)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txtTelHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lblPassHospede)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txtPassHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(64)
        					.addComponent(btnAddHospede, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(347))
        );
        getContentPane().setLayout(layout);

        pack();
    }

    private void txtNomeHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeHospedeActionPerformed

    private void txtRuaHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaHospedeActionPerformed

    private void txtPaisHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisHospedeActionPerformed

    private void btnAddHospedeAction(java.awt.event.ActionEvent evt) {
    	Endereco endereco = new Endereco();
    	endereco.setBairro(txtBairroHospede.getText());
    	endereco.setCep(txtCepHospede.getText());
    	endereco.setCidade(txtCidadeHospede.getText());
    	endereco.setEstado(txtEstadoHospede.getText());
    	endereco.setComplemento(txtCompHospede.getText());
    	endereco.setNumero(txtNumHospede.getText());
    	endereco.setPais(txtPaisHospede.getText());
    	endereco.setRua(txtRuaHospede.getText());
    	
    	Hospede hospede = new Hospede();
    	hospede.setCpf(txtBuscaCpfHospede.getText());
    	hospede.setEmail(txtEmailHospede.getText());
    	hospede.setNome(txtNomeHospede.getText());
    	hospede.setPalavraPasse(txtPassHospede.getText());
    	hospede.setTelefone(txtTelHospede.getText());
    	
    	
    	this.criarHospede(hospede, endereco);
    }

    
    private javax.swing.JButton btnAddHospede;
    private javax.swing.JLabel lblBairroHospede;
    private javax.swing.JLabel lblEstadoHospede;
    private javax.swing.JLabel lblCepHospede;
    private javax.swing.JLabel lblCidadeHospede;
    private javax.swing.JLabel lblCompHospede;
    private javax.swing.JLabel lblBuscaCpfHospede;
    private javax.swing.JLabel lblEmailHospede;
    private javax.swing.JLabel lblNomeHospede;
    private javax.swing.JLabel lblNumHospede;
    private javax.swing.JLabel lblPaisHospede;
    private javax.swing.JLabel lblPassHospede;
    private javax.swing.JLabel lblRuaHospede;
    private javax.swing.JLabel lblTelHospede;
    private javax.swing.JTextField txtBairroHospede;
    private javax.swing.JTextField txtEstadoHospede;
    private javax.swing.JTextField txtCepHospede;
    private javax.swing.JTextField txtCidadeHospede;
    private javax.swing.JTextField txtCompHospede;
    private javax.swing.JTextField txtBuscaCpfHospede;
    private javax.swing.JTextField txtEmailHospede;
    private javax.swing.JTextField txtNomeHospede;
    private javax.swing.JTextField txtNumHospede;
    private javax.swing.JTextField txtPaisHospede;
    private javax.swing.JTextField txtPassHospede;
    private javax.swing.JTextField txtRuaHospede;
    private javax.swing.JTextField txtTelHospede;
    private JTextField textField;
}
=======
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.ifpe.hosp3.view;
import java.awt.Color;

import javax.swing.JOptionPane;

import com.br.ifpe.hosp3.controller.HospedeController;
import com.br.ifpe.hosp3.model.Endereco;
import com.br.ifpe.hosp3.model.Hospede;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.JPanel;
import java.awt.FlowLayout;
import com.jgoodies.forms.factories.DefaultComponentFactory;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Thaysa Gomes
 */
public class TelaCriarHospede extends javax.swing.JInternalFrame {


	/**
	 * Método de ação na interface para criar hospede 
	 * 
	 * @param hospede {@link Hospede}
	 * @param endereco {@link Endereco}
	 * 
	 * @throws Exception
	 **/
	public void criarHospede(Hospede hospede, Endereco endereco) {
		try {
			HospedeController.criarHospede(hospede, endereco);
			JOptionPane.showMessageDialog(null, "Hospede " + hospede.getNome() + "Cadastrado com Sucesso!");
			this.dispose();
		}catch(Exception e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
			this.dispose();
		}
		
	}

    /**
     * Cria nova tela de Hóspede
     */
    public TelaCriarHospede() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	

    	lblEstadoHospede = new javax.swing.JLabel();
    	txtEstadoHospede = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Hóspede");
        
        Color cor = new Color(46,139, 87);
        getContentPane().setLayout(null);
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setBounds(0, 0, 552, 485);
        getContentPane().add(scrollPane);
        
        panel = new JPanel();
        scrollPane.setViewportView(panel);
        panel.setLayout(null);
        
        lblNomeHospede = new javax.swing.JLabel();
        lblNomeHospede.setBounds(42, 57, 34, 14);
        panel.add(lblNomeHospede);
        
        lblNomeHospede.setText("Nome");
        txtNomeHospede = new javax.swing.JTextField();
        txtNomeHospede.setBounds(41, 73, 154, 23);
        panel.add(txtNomeHospede);
        
        lblEmailHospede = new JLabel("E-mail");
        lblEmailHospede.setBounds(41, 111, 46, 14);
        panel.add(lblEmailHospede);
        
        txtEmailHospede = new JTextField();
        txtEmailHospede.setBounds(41, 129, 247, 23);
        panel.add(txtEmailHospede);
        txtEmailHospede.setColumns(10);
        
        lblRua = new JLabel("Rua");
        lblRua.setBounds(183, 163, 46, 14);
        panel.add(lblRua);
        txtRuaHospede = new javax.swing.JTextField();
        txtRuaHospede.setBounds(183, 180, 220, 23);
        panel.add(txtRuaHospede);
        
                txtRuaHospede.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtRuaHospedeActionPerformed(evt);
                    }
                   
                });
        
        JLabel label = new JLabel();
        label.setBounds(244, 57, 19, 14);
        panel.add(label);
        label.setText("CPF");
        
        txtCpf = new JTextField();
        txtCpf.setBounds(245, 73, 220, 23);
        panel.add(txtCpf);
        txtCpf.setColumns(10);
        
        lblCepHospede = new JLabel("CEP");
        lblCepHospede.setBounds(41, 223, 46, 14);
        panel.add(lblCepHospede);
        
        txtCepHospede = new JTextField();
        txtCepHospede.setBounds(41, 241, 107, 23);
        panel.add(txtCepHospede);
        txtCepHospede.setColumns(10);
        
        lblBairroHospede = new JLabel("Bairro");
        lblBairroHospede.setBounds(344, 275, 63, 14);
        panel.add(lblBairroHospede);
        
        txtBairroHospede = new JTextField();
        txtBairroHospede.setBounds(344, 294, 121, 23);
        panel.add(txtBairroHospede);
        txtBairroHospede.setColumns(10);
        
        lblPaisHospede = new JLabel("Pa\u00EDs");
        lblPaisHospede.setBounds(182, 223, 46, 14);
        panel.add(lblPaisHospede);
        
        txtPaisHospede = new JTextField();
        txtPaisHospede.setBounds(182, 241, 106, 23);
        panel.add(txtPaisHospede);
        txtPaisHospede.setColumns(10);
        
        lblCidadeHospede = new JLabel("Cidade");
        lblCidadeHospede.setBounds(323, 223, 46, 14);
        panel.add(lblCidadeHospede);
        
        txtCidadeHospede = new JTextField();
        txtCidadeHospede.setBounds(323, 241, 142, 23);
        panel.add(txtCidadeHospede);
        txtCidadeHospede.setColumns(10);
        
        lblEstadoHospede_1 = new JLabel("Estado");
        lblEstadoHospede_1.setBounds(41, 275, 46, 14);
        panel.add(lblEstadoHospede_1);
        
        txtEstadoHospede_1 = new JTextField();
        txtEstadoHospede_1.setBounds(41, 294, 86, 23);
        panel.add(txtEstadoHospede_1);
        txtEstadoHospede_1.setColumns(10);
        
        lblPassHospede = new JLabel("Palavra passe");
        lblPassHospede.setBounds(323, 116, 107, 14);
        panel.add(lblPassHospede);
        
        txtPassHospede = new JTextField();
        txtPassHospede.setBounds(323, 132, 142, 20);
        panel.add(txtPassHospede);
        txtPassHospede.setColumns(10);
        
        lblCompHospede = new JLabel("Complemento");
        lblCompHospede.setBounds(156, 275, 86, 14);
        panel.add(lblCompHospede);
        
        txtCompHospede = new JTextField();
        txtCompHospede.setBounds(156, 294, 155, 23);
        panel.add(txtCompHospede);
        txtCompHospede.setColumns(10);
        
        lblTelHospede = new JLabel("Telefone");
        lblTelHospede.setBounds(42, 163, 134, 14);
        panel.add(lblTelHospede);
        
        txtTelHospede = new JTextField();
        txtTelHospede.setBounds(42, 181, 120, 23);
        panel.add(txtTelHospede);
        txtTelHospede.setColumns(10);
        
        lblNumHospede = new JLabel("N\u00FAmero");
        lblNumHospede.setBounds(420, 163, 46, 14);
        panel.add(lblNumHospede);
        
        txtNumHospede = new JTextField();
        txtNumHospede.setBounds(420, 179, 46, 23);
        panel.add(txtNumHospede);
        txtNumHospede.setColumns(10);
                
                JLabel lblCadastrarHspede = DefaultComponentFactory.getInstance().createTitle("Cadastrar Hóspede");
                lblCadastrarHspede.setFont(new Font("Tahoma", Font.PLAIN, 14));
                lblCadastrarHspede.setBounds(194, 23, 117, 14);
                panel.add(lblCadastrarHspede);
                
                btnAddHospede = new javax.swing.JButton();
                btnAddHospede.setBounds(370, 350, 95, 35);
                panel.add(btnAddHospede);
                
                        //btnAddHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("./../resources/img/"))); // NOI18N /*iconfinder*/
                        btnAddHospede.setText("Adicionar");
                        btnAddHospede.setBackground(cor);
                        btnAddHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        btnAddHospede.setPreferredSize(new java.awt.Dimension(80, 50));
                        
                        JButton btnCancelar = new JButton("Cancelar");
                        btnCancelar.addActionListener(new ActionListener() {
                        	public void actionPerformed(ActionEvent arg0) {
                        	}
                        });
                        btnCancelar.setBackground(new Color(0, 128, 0));
                        btnCancelar.setBounds(265, 350, 95, 35);
                        panel.add(btnCancelar);
                
       //Adicionando evento para botão de salvar ouvir
                btnAddHospede.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    	btnAddHospedeAction(evt);
                    }
                });
        
                txtNomeHospede.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtNomeHospedeActionPerformed(evt);
                    }
                });

        pack();
    }

    private void txtNomeHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeHospedeActionPerformed

    private void txtRuaHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaHospedeActionPerformed

    private void btnAddHospedeAction(java.awt.event.ActionEvent evt) {
    	Endereco endereco = new Endereco();
    	endereco.setBairro(txtBairroHospede.getText());
    	endereco.setCep(txtCepHospede.getText());
    	endereco.setCidade(txtCidadeHospede.getText());
    	endereco.setEstado(txtEstadoHospede_1.getText());
    	endereco.setComplemento(txtCompHospede.getText());
    	endereco.setNumero(txtNumHospede.getText());
    	endereco.setPais(txtPaisHospede.getText());
    	endereco.setRua(txtRuaHospede.getText());
    	
    	Hospede hospede = new Hospede();
    	hospede.setCpf(txtCpf.getText());
    	hospede.setEmail(txtEmailHospede.getText());
    	hospede.setNome(txtNomeHospede.getText());
    	hospede.setPalavraPasse(txtPassHospede.getText());
    	hospede.setTelefone(txtTelHospede.getText());
    	
    	
    	this.criarHospede(hospede, endereco);
    }

    
    private javax.swing.JButton btnAddHospede;
    private javax.swing.JLabel lblNomeHospede;
    private javax.swing.JTextField txtNomeHospede;
    private javax.swing.JTextField txtRuaHospede;
    private JLabel lblEmailHospede;
    private JTextField txtEmailHospede;
    private JLabel lblRua;
    private JTextField txtCpf;
    private JLabel lblNumHospede;
    private JTextField txtNumHospede;
    private JLabel lblCepHospede;
    private JTextField txtCepHospede;
    private JLabel lblBairroHospede;
    private JTextField txtBairroHospede;
    private JLabel lblPaisHospede;
    private JTextField txtPaisHospede;
    private JLabel lblCidadeHospede;
    private JTextField txtCidadeHospede;
    private JLabel lblEstadoHospede;
    private JLabel lblEstadoHospede_1;
    private JTextField txtEstadoHospede;
    private JTextField txtEstadoHospede_1;
    private JLabel lblPassHospede;
    private JTextField txtPassHospede;
    private JLabel lblCompHospede;
    private JTextField txtCompHospede;
    private JLabel lblTelHospede;
    private JTextField txtTelHospede;
    private JPanel panel;
}
>>>>>>> 316b16771f7991dfbae3b7938846643de513efa5
