	/*
	 * To change this license header, choose License Headers in Project Properties.
	 * To change this template file, choose Tools | Templates
	 * and open the template in the editor.
	 */
	package com.br.ifpe.hosp3.view;
	
	import java.awt.Component;
	import java.io.IOException;
	import java.text.DateFormat;
	import java.util.Date;
	import java.util.logging.Level;
	import java.util.logging.Logger;
	import javax.swing.JOptionPane;
	
	/**
	 *
	 * @author Thaysa Gomes
	 */
	public class TelaPrincipal extends javax.swing.JFrame {
	
	    /**
	     * Cria nova tela Principal
	     */
	    public TelaPrincipal() {
	        initComponents();
	    }
	
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {
	
	        desktop = new javax.swing.JDesktopPane();
	        lblUsuario = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        lblData = new javax.swing.JLabel();
	        jLabel1 = new javax.swing.JLabel();
	        Menu = new javax.swing.JMenuBar();
	        menuCadastro = new javax.swing.JMenu();
	        menuCadastroFuncionario = new javax.swing.JMenuItem();
	        menuCadastroHospede = new javax.swing.JMenuItem();
	        menuRelatorio = new javax.swing.JMenu();
	        menuRelatorioHospedagem = new javax.swing.JMenuItem();
	        menuRelatorioConsumo = new javax.swing.JMenuItem();
	        menuOpcoes = new javax.swing.JMenu();
	        menuOpcoesSair = new javax.swing.JMenuItem();
	
	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setTitle("Hotel Renascença - Gerenciamento");
	        setResizable(false);
	        addWindowListener(new java.awt.event.WindowAdapter() {
	            public void windowActivated(java.awt.event.WindowEvent evt) {
	                formWindowActivated(evt);
	            }
	        });
	
	        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
	        desktop.setLayout(desktopLayout);
	        desktopLayout.setHorizontalGroup(
	            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 540, Short.MAX_VALUE)
	        );
	        desktopLayout.setVerticalGroup(
	            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 0, Short.MAX_VALUE)
	        );
	
	        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
	        lblUsuario.setText("Usuário");
	
	        lblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        lblData.setText("Data");
	
	        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/ifpe/hosp3/icons/logo.png"))); // NOI18N
	
	        menuCadastro.setText("Cadastro");
	        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                menuCadastroActionPerformed(evt);
	            }
	        });
	
	        menuCadastroFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
	        menuCadastroFuncionario.setText("Funcionário");
	        menuCadastroFuncionario.setEnabled(false);
	        menuCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                menuCadastroFuncionarioActionPerformed(evt);
	            }
	        });
	        menuCadastro.add(menuCadastroFuncionario);
	
	        menuCadastroHospede.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
	        menuCadastroHospede.setText("Hóspede");
	        menuCadastroHospede.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                menuCadastroHospedeActionPerformed(evt);
	            }
	        });
	        menuCadastro.add(menuCadastroHospede);
	
	        Menu.add(menuCadastro);
	
	        menuRelatorio.setText("Relatório");
	        menuRelatorio.setEnabled(false);
	
	        menuRelatorioHospedagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
	        menuRelatorioHospedagem.setText("Hospedagem");
	        menuRelatorio.add(menuRelatorioHospedagem);
	
	        menuRelatorioConsumo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
	        menuRelatorioConsumo.setText("Consumo Extra");
	        menuRelatorio.add(menuRelatorioConsumo);
	
	        Menu.add(menuRelatorio);
	
	        menuOpcoes.setText("Opções");
	        menuOpcoes.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                menuOpcoesActionPerformed(evt);
	            }
	        });
	
	        menuOpcoesSair.setText("Sair");
	        menuOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                menuOpcoesSairActionPerformed(evt);
	            }
	        });
	        menuOpcoes.add(menuOpcoesSair);
	
	        Menu.add(menuOpcoes);
	
	        setJMenuBar(Menu);
	
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
	                        .addComponent(jLabel2)
	                        .addGap(40, 40, 40)
	                        .addComponent(jLabel1)
	                        .addGap(49, 49, 49))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(30, 30, 30)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(lblData)
	                            .addComponent(lblUsuario))
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(desktop)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(62, 62, 62)
	                .addComponent(lblUsuario)
	                .addGap(18, 18, 18)
	                .addComponent(lblData)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(79, 79, 79))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jLabel1)
	                        .addGap(61, 61, 61))))
	        );
	
	        pack();
	        setLocationRelativeTo(null);
	    }// </editor-fold>//GEN-END:initComponents
	    /**
	     * 
	     * Método para abrir a janela de cadastro de Funcionário
	     */
	    private void menuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFuncionarioActionPerformed
	        TelaFuncionario funcionario = null;
	        try {
	            funcionario = new TelaFuncionario();
	        } catch (IOException ex) {
	            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
	        }
	        funcionario.setVisible(true);
	        desktop.add(funcionario);
	    }//GEN-LAST:event_menuCadastroFuncionarioActionPerformed
	/**
	     * 
	     * Método para formatar a data da tela principal
	     */
	    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
	        Date data = new Date();
	        DateFormat formataData = DateFormat.getDateInstance(DateFormat.SHORT);
	        lblData.setText(formataData.format(data));
	
	    }//GEN-LAST:event_formWindowActivated
	
	    private void menuOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcoesActionPerformed
	      
	    }//GEN-LAST:event_menuOpcoesActionPerformed
	/**
	     * 
	     * Método sair do sistema
	     */
	    private void menuOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcoesSairActionPerformed
	        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Alerta", JOptionPane.YES_NO_OPTION);
	
	        if (sair == JOptionPane.YES_OPTION) {
	            System.exit(0);
	        }
	    }//GEN-LAST:event_menuOpcoesSairActionPerformed
	/**
	     * 
	     * Método para abrir a janela de cadastro de Hóspede
	     */
	    private void menuCadastroHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroHospedeActionPerformed
	        TelaCriarHospede hospede = new TelaCriarHospede();
	        hospede.setVisible(true);
	        Component add;
	        add = desktop.add(hospede);
	    }//GEN-LAST:event_menuCadastroHospedeActionPerformed
	
	    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
	        
	    }//GEN-LAST:event_menuCadastroActionPerformed
	
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	
	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(() -> {
	            new TelaPrincipal().setVisible(true);
	        });
	    }
	
	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JMenuBar Menu;
	    private javax.swing.JDesktopPane desktop;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel lblData;
	    public static javax.swing.JLabel lblUsuario;
	    private javax.swing.JMenu menuCadastro;
	    public static javax.swing.JMenuItem menuCadastroFuncionario;
	    private javax.swing.JMenuItem menuCadastroHospede;
	    private javax.swing.JMenu menuOpcoes;
	    private javax.swing.JMenuItem menuOpcoesSair;
	    public static javax.swing.JMenu menuRelatorio;
	    private javax.swing.JMenuItem menuRelatorioConsumo;
	    private javax.swing.JMenuItem menuRelatorioHospedagem;
	    // End of variables declaration//GEN-END:variables
	}
