/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.ifpe.hosp3.view;
import java.awt.Font;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.br.ifpe.hosp3.controller.QuartoController;
import com.br.ifpe.hosp3.model.Quarto;
import com.jgoodies.forms.factories.DefaultComponentFactory;

/**
 *
 * @author THG
 */
public class TelaCriarQuarto extends javax.swing.JInternalFrame {

	private boolean alterar = false;
	private JLabel title;
	private Quarto quarto = new Quarto();
    /**
     * Creates new form TelaCriarQuarto
     */
    public TelaCriarQuarto() {
        initComponents();
    }
    public TelaCriarQuarto(Quarto quarto) {
    	this();
    	setFields(quarto);
    	this.alterar = true;
    }

    /**
     * Método de ação na interface para criação de quarto
     * @param quarto {@link Quarto}
     * @throws Exception
     **/
    public void criarQuarto(Quarto quarto) {
    	try {
    		QuartoController quartoController = new QuartoController();
    		quartoController.criarQuarto(quarto);
    		JOptionPane.showMessageDialog(null, "Quarto "+ quarto.getNumero() + "íncluido com sucesso");
    		this.setClosed(true);
    		this.dispose();
    		
    	}catch(Exception e) {
    		JOptionPane.showMessageDialog(null, e.getMessage());
    	}
    }
    
    public void alterarQuarto(Quarto quarto) {
    	try {
    		QuartoController quartoController = new QuartoController();
    		quartoController.alterarQuarto(quarto);
    		JOptionPane.showMessageDialog(null, "Quarto "+ quarto.getNumero() + " alterado com sucesso");
    		this.setClosed(true);
    		this.dispose();
    		
    	}catch(Exception e) {
    		JOptionPane.showMessageDialog(null, e.getMessage());
    	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        txtCpfFunc = new javax.swing.JTextField();
        lblCpfFunc = new javax.swing.JLabel();
        lblCpfFunc1 = new javax.swing.JLabel();
        lblCpfFunc1.setBounds(340, 146, 24, 14);
        boxTipo = new javax.swing.JComboBox<>();
        boxTipo.setBounds(340, 167, 121, 23);
        btnSalvar = new javax.swing.JButton();
        btnSalvar.setBounds(321, 272, 74, 24);

        lblCpfFunc.setText("CPF");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quarto");
        setPreferredSize(new java.awt.Dimension(540, 467));

        lblCpfFunc1.setText("Tipo");

        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples", "Suite" }));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(boxTipo);
        getContentPane().add(lblCpfFunc1);
        getContentPane().add(btnSalvar);
        
        textNumero = new JTextField();
        textNumero.setBounds(340, 87, 121, 23);
        getContentPane().add(textNumero);
        textNumero.setColumns(10);
        
        textQtdPessoas = new JTextField();
        textQtdPessoas.setBounds(106, 86, 142, 24);
        getContentPane().add(textQtdPessoas);
        textQtdPessoas.setColumns(10);
        
        textValor = new JTextField();
        textValor.setBounds(106, 172, 140, 24);
        getContentPane().add(textValor);
        textValor.setColumns(10);
        
        JLabel lblQuantidadeDePessoas = new JLabel("Quantidade de pessoas");
        lblQuantidadeDePessoas.setBounds(106, 60, 152, 14);
        getContentPane().add(lblQuantidadeDePessoas);
        
        JLabel lblValor = new JLabel("Valor");
        lblValor.setBounds(106, 146, 55, 14);
        getContentPane().add(lblValor);
        
        JLabel lblNmero = new JLabel("Número");
        lblNmero.setBounds(340, 60, 55, 14);
        getContentPane().add(lblNmero);
        
        btnCancelar = new JButton("Cancelar");
        btnCancelar.setBounds(148, 272, 98, 24);
        getContentPane().add(btnCancelar);
        
        title = DefaultComponentFactory.getInstance().createTitle("Novo Quarto");
        title.setFont(new Font("Dialog", Font.BOLD, 15));
        title.setBounds(243, 12, 90, 14);
        getContentPane().add(title);

        pack();
    }
    
    private void setFields(Quarto quarto) {
    	this.quarto = quarto;
    	textNumero.setText(quarto.getNumero());
    	textQtdPessoas.setText(String.valueOf(quarto.getQuantidadePessoas()));
    	textValor.setText(String.valueOf(quarto.getValor()));
    	
    	this.title.setText("Alterar Quarto");
    	
    	
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
 
    	this.quarto.setNumero(textNumero.getText());
    	this.quarto.setQuantidadePessoas(Integer.parseInt(textQtdPessoas.getText()));
    	this.quarto.setTipo(boxTipo.getToolTipText());
    	this.quarto.setValor(Float.parseFloat(textValor.getText()));
    	this.quarto.setTipo(boxTipo.getModel().getSelectedItem().toString());
    	
    	if(!this.alterar) {
        	this.criarQuarto(this.quarto);
    	}else{
    		this.alterarQuarto(this.quarto);
    	}
    	
        
    }


    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JLabel lblCpfFunc;
    private javax.swing.JLabel lblCpfFunc1;
    private javax.swing.JTextField txtCpfFunc;
    private JTextField textNumero;
    private JTextField textQtdPessoas;
    private JTextField textValor;
}
